### ISSUE TITLE
Legyen HTTPS

### ISSUE THREAD

**Issue by lberki** [lptr/sarok.org#13]
...vagy még inkább *csak* HTTPS. 

Let's Encrypt tanúsítvány, 'szt csá.

**Comment by lberki** [comment]
Installaltam a `certbot-auto`-t. Most mar van HTTPS, igaz, meg ki kell talalni, hogyan beszeljem ra a PHP-t, hogy ne HTTP resource-okat akarjon kerni HTTPS lapokon, mert az ugye nem megy.

**Comment by pppq** [comment]
Úúú, nagy bigup mindkettőtöknek! 👍 

Ezt az Apache konfigban, vagy a `.htaccess` piszkálásával a legkönnyebb megejteni, főleg a linkek + képek miatt, amik fixen vannak belesütve a bejegyzésekbe:
https://wiki.apache.org/httpd/RedirectSSL
https://wiki.apache.org/httpd/RewriteHTTPToHTTPS

**Comment by lptr** [comment]
Ki vagy, @pppq? :)

**Comment by pppq** [comment]
Akinek a felhasználói nevének első két betűje a pull request, utolsó három betűje pedig a teletype rövidítése. 😄

**Comment by sarokuser1** [comment]
Got it! A Let's Encrypt eleg meno, megcsinalta az osszes SSL hekkelest, amit csak el tudok kepzelni :)

Most, hogy mar van forras-hozzaferesem, megcsinalhatom a teljes HTTPS-t... ha nem lennek hozza lusta, I mean, de lassuk, milyen messze jutok ma.

**Comment by sarokuser1** [comment]
Sajna a mod_rewrite-s megoldas nem fog menni; a bongeszok nem engedik, hogy HTTP-s eroforrasokat hasznaljon fel egy HTTPS-es oldal, szoval hiaba redirectel a HTTP HTTPS-re, a bongeszo el se inditja a kerest. Ugyhogy marad a forraskod-hekkeles.

**Comment by sarokuser1** [comment]
0dadadc362c808c45c6045783b602baab7ab0101 utan a linkek HTTPS, csakkor, ha a lap is HTTPS (milyen szep commithash!)

**Comment by sarokuser1** [comment]
HTTP -> HTTPS redirect abszolvalva. Megneztem egy `img.sarok.org`-os kepet, es az is mukodik. Igyhat ezt most lezarom, a Facebookra meg bepostolom, hogy tessek kiprobalni.
