### ISSUE TITLE
HTTPS certificate lejárt

### ISSUE THREAD

**Issue by pppq** [lptr/sarok.org#14]
Július végétől (#13) most pörgött le a 90 nap:

![image](https://user-images.githubusercontent.com/8782039/47607249-ef63c500-da1d-11e8-918d-0f9b6872febb.png)

**Comment by lberki** [comment]
`~/certbot-auto renew` megoldotta. Majd egyszer kéne belerakni a crontabba, de három havonta egyszer ránézni a szerverre végülis nem valami nagy erőfeszítés...
