### ISSUE TITLE
DB schema dump

### ISSUE THREAD

**Issue by pppq** [lptr/sarok.org#15]
Szeretnék egy ilyet kérni a repositoryba:

```bash
$ mysqldump --no-data -u ${db_user} -p${db_pass} sarok > schema.sql
```

Nagyon hiányzik egy sandbox összehegesztéséhez; a kódból elég körülményes összeollózni a sémát (bár nem lehetetlen).

**Comment by sarokuser1** [comment]
Íme. Közben megheggesztettem a certificate-t is, ha már arra jártam.
