### ISSUE TITLE
Fixaljuk a helyhianyt

### ISSUE THREAD

**Issue by lptr** [lptr/sarok.org#5]
Jelenleg alig van hely a gepen, amin a sarok fut. Lehet, hogy at kene rakni valami mas vasra, amin tobb hely van, vagy valahogy a meglevo alatt kiboviteni. A 20 GB-bol 19 hasznalatban van, es nem nagyon van mit torolni.

A backupoknak (#1, #2) is kell hely, szoval ezt lehet, hamar meg kene oldani.

**Comment by lberki** [comment]
`/var/mail/www-data` 11 giga (!).  Ennek ket oka van:

* Olyan levelek jonnek, hogy `Table './sarok3/accesslog is marked as crashed...` . 
* Ezek a levelek a `system@sarok.org` cimre mennek a `www-data@d1stkfactory`-tol, es azt mondja az exim, hogy a sarok.org remote domain.

Asszem, mindkettot meg kellene fixalni... de mivel a legelso level 2014 oktoberbol jon, szerintem atmenetileg le lehet oket torolni, oszt jovan.

**Comment by lberki** [comment]
@lptr , azt mondtad, van valami backupod. Visszallithato? Nekiallnek lefuttatni egy `myisamchk`-t az adatbazison, de elotte azert jo lenne, ha biztos lennek benne, hogy vissza tudom allitani, ha elszabom...

**Comment by lberki** [comment]
...addig egyszeruen letoroltem az e-maileket a `www-data` mailboxabol. 10 giga felszabaditva. Ugy nez ki, kb. 50K/perc sebesseggel jonnek a szambol a fergek^H^H^Hlevelek.

**Comment by lberki** [comment]
`myisamchk --recover -f -v accesslog.MYI` utan a levelek tobbet nem jonnek, ugyhogy a problemat megoldottnak nyilvanitom. Yay!

**Comment by lptr** [comment]
Eljen! Bar ez csak az egyik oka a helyhianynak.
