### ISSUE TITLE
Uj kontent letrehozas ujra-engedelyezese

### ISSUE THREAD

**Issue by lptr** [lptr/sarok.org#9]
Ehhez ki kell elobb talalni, hogy mi legyen a kovetkezo problemakkal:

- [ ] plusz hardver igeny a megnovekedett forgalomhoz
- [ ] moderalas, egyeb emberi problemakat ki kezeli

**Comment by sarokuser1** [comment]
Szóval az van, hogy minél többet foglalkozok vele, annál lelkesebb vagyok és viszket a tűzgombon az ujjam. Pontokba szedve:

* A hardver... max. lassú lesz, ha meg igen, szerzünk egy nagyobb GCE/AWS/OVH gépet
* A moderálással mennyi para van. Nem lehet ezt online kitalálni?
* Ahogy látom, a stabilitással nem lesz sok gond, max logokat kell törölgetni néha.

**Comment by sarokuser1** [comment]
Tekintve, hogy lassan egy éve megint írható az adatbázis, ezt lezárom.

Nem mintha a fentebb említett problémákra lenne megoldás, de egy évig nem volt velük gond, szóval optimista vagyok. Ha meg igen, max. megint read only-va tesszük.
